<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account Settings' => 'ตั้งค่าบัญชี',
    'Profile settings' => 'ตั้งค่าข้อมูลส่วนตัว',
    'Settings' => 'ตั้งค่า',
    'User Settings' => 'จัดการข้อมูลผู้ใช้',
    'About' => 'เกี่ยวกับเรา',
    'Articles' => 'บทความ',
    'Attachments' => 'ไฟล์แนบ',
    'Backend' => 'Backend',
    'Body' => 'Cuerpo',
    'Check your email for further instructions.' => 'Check your email for further instructions.',
    'Confirm Password' => 'ยืนยันรหัสผ่าน',
    'Contact' => 'ติดต่อ',
    'E-mail' => 'อีเมล์',
    'Email' => 'อีเมล์',
    'Error while oauth process.' => 'Error while oauth process.',
    'Female' => 'หญิง',
    'Home' => 'หน้าหลัก',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'หากคุณลืมรหัสผ่าน <a href="{link}">คลิกที่นี่</a>',
    'Incorrect username or password.' => 'Incorrect username or password.',
    'Language' => 'เลือกภาษา',
    'Log in with' => 'ล็อกอินด้วยบัญชี',
    'Login' => 'เข้าสู่ระบบ',
    'Logout' => 'ออกจากระบบ',
    'Male' => 'ชาย',
    'Name' => 'ชื่อ',
    'Need an account? Sign up.' => 'หากคุณยังไม่เป็นสามาชิก? ลงทะเบียนได้ที่นี่',
    'New password was saved.' => 'New password was saved.',
    'Page not found' => 'Page not found.',
    'Password' => 'รหัสผ่าน',
    'Password reset for {name}' => 'กูรหันผา่นสำหรับ {name}',
    'Remember Me' => 'ล็อกอินอัตโนมัติครั้งต่อไป',
    'Request password reset' => 'Request password reset',
    'Reset password' => 'เปลี่ยนรหัสผ่าน',
    'Sign up with' => 'ล็อกอินด้วยบัญชี',
    'Signup' => 'ลงทะเบียน',
    'Sorry, we are unable to reset password for email provided.' => 'Sorry, we are unable to reset password for email provided.',
    'Subject' => 'ชื่อเรื่อง',
    'Submit' => 'บันทึก',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Thank you for contacting us. We will respond to you as soon as possible.',
    'There was an error sending email.' => 'There was an error sending email.',
    'This email address has already been taken.' => 'This email address has already been taken.',
    'This username has already been taken.' => 'This username has already been taken.',
    'Update' => 'แก้ไข',
    'Username' => 'ชื่อบัญชี',
    'Username or email' => 'ชื่อบัญชีหรืออีเมล์',
    'Verification Code' => 'รหัสใช้ยืนยันการเข้าใช้งาน',
    'We already have a user with email {email}' => 'We already have a user with email {email} ',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Welcome to {app-name}. Email with your login information was sent to your email.',
    'Your account has been successfully saved' => 'Your account has been successfully saved',
    '{app-name} | Your login information' => '{app-name} |  Your login information',
    'Researches'=>'ทะเบียน<span>งานวิจัย</span>',
    'Submission'=>'Submission',
    'Create Research'=>'ลงทะเบียนงานวิจัย',
    'Edit Research'=>'แก้ไขงานวิจัย',
    'Attach File'=>'แนบไฟล์เอกสาร'
];
